"""
TRINETRA — Incident Report Generator (Phase 9)

Generates structured incident reports from email detection data.
Reports are exported as structured dicts (JSON-serializable).

Report scope:
  - Incident ID, detection time, case metadata
  - Sender / domain / URL / IP entities
  - Matched threat indicators (CERT-In, Local DB, etc.)
  - All evidence from detection layers
  - Risk score, severity, decision
  - Recommended SOC action

IMPORTANT: Reports are NEVER automatically submitted externally.
Export is analyst-initiated only.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from app.services.threat_providers import NormalizedIndicator


# ---------------------------------------------------------------------------
# Report Data Models
# ---------------------------------------------------------------------------


class IndicatorReportEntry(BaseModel):
    indicator: str
    indicator_type: str
    source: str
    advisory_id: Optional[str] = None
    severity: str
    confidence: float
    description: Optional[str] = None
    source_url: Optional[str] = None
    timestamp: Optional[str] = None


class IncidentReport(BaseModel):
    """
    Structured incident report for analyst review and audit.
    NOT automatically submitted to external services.
    """
    report_id: str = Field(default_factory=lambda: f"TRINETRA-INC-{uuid.uuid4().hex[:8].upper()}")
    generated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    report_version: str = "1.0"

    # Case Metadata
    incident_id: Optional[str] = None
    detection_time: Optional[str] = None
    email_message_id: Optional[str] = None
    email_subject: Optional[str] = None

    # Email Entities
    sender: Optional[str] = None
    sender_domain: Optional[str] = None
    recipient: Optional[str] = None
    urls: List[str] = []
    domains: List[str] = []
    ips: List[str] = []

    # Authentication
    spf_result: Optional[str] = None
    dkim_result: Optional[str] = None
    dmarc_result: Optional[str] = None

    # Risk Assessment
    final_risk_score: float = 0.0
    severity: str = "LOW"
    decision: str = "ALLOW"
    confidence: float = 0.0

    # Layer Scores
    content_risk: float = 0.0
    url_risk: float = 0.0
    identity_risk: float = 0.0
    threat_intel_risk: float = 0.0
    graph_risk: float = 0.0

    # Threat Indicators
    threat_indicators: List[IndicatorReportEntry] = []

    # Evidence & Explanation
    evidence: Dict[str, Any] = {}
    explanation_summary: Optional[str] = None
    recommended_action: Optional[str] = None

    # Audit metadata
    analyst_feedback: Optional[str] = None
    analyst_comments: Optional[str] = None

    disclaimer: str = (
        "This report is generated by TRINETRA for SOC analyst review only. "
        "Do NOT automatically submit this report to external services. "
        "Analyst verification is required before any external action."
    )


# ---------------------------------------------------------------------------
# Report Builder
# ---------------------------------------------------------------------------


def build_incident_report(
    *,
    incident_id: Optional[str] = None,
    detection_time: Optional[datetime] = None,
    email_message_id: Optional[str] = None,
    email_subject: Optional[str] = None,
    sender: Optional[str] = None,
    sender_domain: Optional[str] = None,
    recipient: Optional[str] = None,
    urls: Optional[List[str]] = None,
    domains: Optional[List[str]] = None,
    ips: Optional[List[str]] = None,
    spf_result: Optional[str] = None,
    dkim_result: Optional[str] = None,
    dmarc_result: Optional[str] = None,
    final_risk_score: float = 0.0,
    severity: str = "LOW",
    decision: str = "ALLOW",
    confidence: float = 0.0,
    content_risk: float = 0.0,
    url_risk: float = 0.0,
    identity_risk: float = 0.0,
    threat_intel_risk: float = 0.0,
    graph_risk: float = 0.0,
    matched_indicators: Optional[List[NormalizedIndicator]] = None,
    evidence: Optional[Dict[str, Any]] = None,
    explanation_summary: Optional[str] = None,
    recommended_action: Optional[str] = None,
    analyst_feedback: Optional[str] = None,
    analyst_comments: Optional[str] = None,
) -> IncidentReport:
    """
    Assembles a complete IncidentReport from detection pipeline outputs.

    All fields are optional — the report is built from whatever data is available.
    """
    # Build indicator entries from matched TI indicators
    indicator_entries: List[IndicatorReportEntry] = []
    for ind in (matched_indicators or []):
        ts = ind.last_seen.isoformat() if ind.last_seen else None
        indicator_entries.append(IndicatorReportEntry(
            indicator=ind.indicator,
            indicator_type=ind.indicator_type,
            source=ind.source,
            advisory_id=ind.advisory_id,
            severity=ind.severity,
            confidence=ind.confidence,
            description=ind.description,
            source_url=ind.source_url,
            timestamp=ts,
        ))

    return IncidentReport(
        incident_id=incident_id,
        detection_time=detection_time.isoformat() if detection_time else None,
        email_message_id=email_message_id,
        email_subject=email_subject,
        sender=sender,
        sender_domain=sender_domain,
        recipient=recipient,
        urls=urls or [],
        domains=domains or [],
        ips=ips or [],
        spf_result=spf_result,
        dkim_result=dkim_result,
        dmarc_result=dmarc_result,
        final_risk_score=final_risk_score,
        severity=severity,
        decision=decision,
        confidence=confidence,
        content_risk=content_risk,
        url_risk=url_risk,
        identity_risk=identity_risk,
        threat_intel_risk=threat_intel_risk,
        graph_risk=graph_risk,
        threat_indicators=indicator_entries,
        evidence=evidence or {},
        explanation_summary=explanation_summary,
        recommended_action=recommended_action,
        analyst_feedback=analyst_feedback,
        analyst_comments=analyst_comments,
    )
