"""
TRINETRA — Explainability API Endpoints (Phase 12)

POST /api/v1/explain/email
    Runs the full 5-layer pipeline + Gemini explanation in one call.
    Accepts raw email fields.

POST /api/v1/explain/bundle
    Accepts a pre-built EvidenceBundle (from an already-evaluated email).

GET  /api/v1/explain/status
    Returns Gemini availability and configuration state.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from app.core.config import settings
from app.core.logging import logger
from app.services.explainability_service import (
    EvidenceBundle,
    PhishingExplanation,
    build_evidence_bundle,
    explain_email,
)

router = APIRouter()


# ---------------------------------------------------------------------------
# Request / Response Schemas
# ---------------------------------------------------------------------------

class ExplainEmailRequest(BaseModel):
    """Raw email fields — the endpoint runs the full pipeline then explains."""

    subject:        str  = Field(..., description="Email subject line")
    plain_text:     str  = Field("",  description="Extracted plain text body")
    sender_email:   Optional[str] = None
    sender_domain:  Optional[str] = None
    recipient:      Optional[str] = None
    timestamp:      Optional[str] = None
    email_id:       Optional[str] = None
    urls:           List[str]     = []
    ips:            List[str]     = []
    headers:        Dict[str, str] = {}


class ExplainBundleRequest(BaseModel):
    """
    Accepts an already-evaluated EvidenceBundle.
    Used when the risk pipeline has already run and the caller wants
    to (re-)generate or refresh the explanation without re-running detection.
    """
    bundle: EvidenceBundle


class ExplainabilityStatusResponse(BaseModel):
    gemini_configured: bool
    gemini_model:      str
    fallback_available: bool
    description:       str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post(
    "/email",
    response_model=PhishingExplanation,
    summary="Run full pipeline and explain",
)
async def explain_from_email(req: ExplainEmailRequest) -> PhishingExplanation:
    """
    Executes the complete 5-layer phishing detection pipeline against raw
    email data, then invokes the Explainable AI layer to generate a
    plain-language explanation of the verdict.

    - Detection verdict: produced by TRINETRA's multi-signal engine.
    - Explanation: generated by Gemini (if configured) or deterministic fallback.
    - Gemini NEVER adds facts beyond the supplied evidence bundle.
    """
    from app.services.risk_engine import evaluate_email_pipeline, ALL_LAYERS

    try:
        # 1. Run detection pipeline
        risk_result = await evaluate_email_pipeline(
            subject=req.subject,
            plain_text=req.plain_text,
            sender_email=req.sender_email,
            sender_domain=req.sender_domain,
            urls=req.urls,
            ips=req.ips,
            headers=req.headers,
            email_id=req.email_id,
        )

        # 2. Build evidence bundle from pipeline result
        bundle = build_evidence_bundle(
            risk_result=risk_result,
            subject=req.subject,
            sender_email=req.sender_email,
            sender_domain=req.sender_domain,
            recipient=req.recipient,
            timestamp=req.timestamp,
            email_id=req.email_id,
        )

        # 3. Generate explanation
        explanation = await explain_email(bundle)
        return explanation

    except Exception as e:
        logger.error("explain_email_endpoint_error", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Explainability pipeline error: {str(e)}",
        )


@router.post(
    "/bundle",
    response_model=PhishingExplanation,
    summary="Explain from pre-built evidence bundle",
)
async def explain_from_bundle(req: ExplainBundleRequest) -> PhishingExplanation:
    """
    Accepts a pre-built EvidenceBundle and generates a plain-language
    explanation from it.

    Useful for re-generating explanations after analyst review, or when
    the risk pipeline has already run and the caller only needs the
    explanation layer.
    """
    try:
        return await explain_email(req.bundle)
    except Exception as e:
        logger.error("explain_bundle_endpoint_error", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Explanation generation error: {str(e)}",
        )


@router.get(
    "/status",
    response_model=ExplainabilityStatusResponse,
    summary="Explainability layer status",
)
async def get_explainability_status() -> ExplainabilityStatusResponse:
    """
    Returns the current configuration and availability of the
    Explainable AI layer. Does not make a live Gemini API call.
    """
    gemini_ok = settings.gemini_configured
    return ExplainabilityStatusResponse(
        gemini_configured=gemini_ok,
        gemini_model="gemini-1.5-flash" if gemini_ok else "none",
        fallback_available=True,
        description=(
            "Gemini explanation active — AI summaries will be generated from system evidence."
            if gemini_ok
            else
            "Gemini not configured (GEMINI_API_KEY missing). "
            "Deterministic fallback explanation active — "
            "TRINETRA detection pipeline operates normally."
        ),
    )
